from flask import Blueprint, render_template_string, redirect, url_for, request, jsonify
from datetime import datetime

# Create the blueprint for tools
tools_bp = Blueprint('tools', __name__, url_prefix='/tools')

# Import sub-blueprints
from .polymarket_monitor import polymarket_monitor_bp

# Tools data - ordered by date (newest first)
cross_chain_tools = [
    {
        "title": "Polymarket Spike Monitor",
        "emoji": "📊",
        "description": "Automated monitoring tool for detecting unusual orderbook activity on Polymarket prediction markets. Collects data every 30 minutes, detects spikes when orderbook depth exceeds 3x baseline, and sends Discord alerts with market details. Features time-series storage in MySQL, auto-cleanup of old data, and a real-time dashboard.",
        "why_valuable": "Detect potential insider trading signals before news breaks",
        "technical_scope": "Polymarket API integration, MySQL time-series, Discord webhooks, cron automation",
        "hiring_impact": "Demonstrates data pipeline engineering and anomaly detection",
        "tags": ["Monitoring"],
        "date": datetime(2025, 2, 4),
        "slug": "polymarket-monitor",
        "status": "live"
    },
    {
        "title": "Chainlink Price Feeds",
        "emoji": "📈",
        "description": "Live cryptocurrency prices powered by Chainlink's decentralized oracle network. Displays real-time BTC, ETH, LINK, AVAX, and MATIC prices fetched directly from Chainlink smart contracts on Ethereum mainnet. Features auto-refresh every 30 seconds, on-chain update timestamps, and direct links to contract addresses on Etherscan.",
        "why_valuable": "Access tamper-proof, decentralized price data directly from Chainlink oracles",
        "technical_scope": "Web3.py integration, Chainlink AggregatorV3 contracts, Ethereum mainnet",
        "hiring_impact": "Demonstrates Web3 development skills and smart contract interaction",
        "tags": ["Price Feeds"],
        "date": datetime(2024, 12, 30),
        "slug": "crypto-prices",
        "status": "live"
    },
    {
        "title": "Reply Assistant",
        "emoji": "🤖",
        "description": "AI-powered social media engagement tool with Discord integration. Monitor X (Twitter) accounts for new posts, get intelligent reply suggestions generated by Claude AI, and post with one-click approval via Discord. Features multi-tier feed fetching (X API, RapidAPI, Nitter fallback), quality scoring, engagement metrics, and comprehensive cost tracking.",
        "why_valuable": "Save hours on social media engagement with AI-powered replies",
        "technical_scope": "Claude AI integration, Discord bot, 3-tier API fallback system",
        "hiring_impact": "Demonstrates AI integration, API orchestration, and full-stack development",
        "tags": ["Social Media"],
        "date": datetime(2024, 12, 10),
        "slug": "reply-assistant",
        "status": "live"
    },
    {
        "title": "Protocol Fee Analyzer",
        "emoji": "💰",
        "description": "Compare transaction costs across DeFi protocols including bridges, DEXs, and lending platforms. Aggregates real-time fee data to help identify the most cost-effective routes for swaps, transfers, and cross-chain operations. Visualize fee trends over time and receive alerts when costs drop below your target thresholds.",
        "why_valuable": "Optimize DeFi costs with comprehensive fee comparison",
        "technical_scope": "Multi-protocol fee aggregation and trend analysis",
        "hiring_impact": "Shows understanding of DeFi economics and data aggregation",
        "tags": ["DeFi Tools"],
        "date": datetime(2025, 9, 23),
        "slug": "protocol-fee-analyzer",
        "status": "coming_soon"
    },
    {
        "title": "Smart Contract Event Explorer",
        "emoji": "🔍",
        "description": "Monitor and visualize on-chain events from any smart contract across multiple EVM chains. Track token transfers, governance votes, liquidity changes, and custom events with real-time notifications. Features historical event timelines, filtering by event type, and exportable data for deeper analysis.",
        "why_valuable": "Gain visibility into on-chain activity with real-time event tracking",
        "technical_scope": "Multi-chain event indexing and real-time WebSocket feeds",
        "hiring_impact": "Demonstrates blockchain data infrastructure expertise",
        "tags": ["Data Visualization"],
        "date": datetime(2025, 9, 23),
        "slug": "event-explorer",
        "status": "coming_soon"
    },
    {
        "title": "Protocol Health Monitor",
        "emoji": "💓",
        "description": "Real-time monitoring dashboard for DeFi protocol health metrics including TVL changes, liquidity depth, oracle freshness, and governance activity. Get instant alerts for unusual patterns that may indicate security risks or market opportunities. Tracks key risk indicators across lending, DEX, and bridge protocols.",
        "why_valuable": "Stay ahead of protocol risks with proactive monitoring",
        "technical_scope": "Multi-source data aggregation and anomaly detection",
        "hiring_impact": "Shows deep understanding of DeFi risk factors",
        "tags": ["Monitoring"],
        "date": datetime(2026, 1, 10),
        "slug": "protocol-monitor",
        "status": "coming_soon"
    },
    {
        "title": "Gas Intelligence Dashboard",
        "emoji": "⛽",
        "description": "Advanced gas price analytics and prediction engine for EVM chains. Visualize historical gas patterns, identify optimal transaction windows, and receive AI-powered recommendations for timing your transactions. Includes network congestion forecasts and mempool analysis for power users.",
        "why_valuable": "Make smarter transaction timing decisions with gas analytics",
        "technical_scope": "ML-based forecasting and mempool data analysis",
        "hiring_impact": "Combines data science with blockchain infrastructure",
        "tags": ["Analytics"],
        "date": datetime(2026, 1, 20),
        "slug": "gas-intelligence",
        "status": "coming_soon"
    },
    {
        "title": "Protocol Security Scanner",
        "emoji": "🛡️",
        "description": "Automated security analysis tool that evaluates smart contract risk factors, admin key configurations, upgrade patterns, and dependency risks. Generates security scorecards based on on-chain data, audit history, and known vulnerability patterns. Helps users and researchers assess protocol safety before interacting.",
        "why_valuable": "Assess protocol security risks with automated analysis",
        "technical_scope": "Static analysis, on-chain risk metrics, and audit aggregation",
        "hiring_impact": "Demonstrates security research and tooling expertise",
        "tags": ["Security"],
        "date": datetime(2026, 2, 1),
        "slug": "security-scanner",
        "status": "coming_soon"
    }
]

# Tools metrics
tools_metrics = {
    "total_tools": len(cross_chain_tools),
    "protocols_integrated": 12,
    "development_hours": 1800,
    "apis_connected": 25
}

# Redirect old trading-suite URL to new tools URL for SEO
@tools_bp.route('/trading-suite')
@tools_bp.route('/trading-suite/')
def redirect_legacy_trading_suite():
    return redirect(url_for('tools.tools'), code=301)

@tools_bp.route('/<slug>')
def tool(slug):
    """Individual tool page"""
    from flask import render_template, abort

    # Reply Assistant has its own blueprint - redirect to it
    if slug == 'reply-assistant':
        return redirect(url_for('reply_assistant.index'))

    # Crypto Prices has its own blueprint - redirect to it
    if slug == 'crypto-prices':
        return redirect(url_for('crypto_prices.index'))

    # Polymarket Monitor has its own blueprint - redirect to it
    if slug == 'polymarket-monitor':
        return redirect(url_for('polymarket_monitor.index'))

    # Find the tool by slug
    tool_data = None
    for tool in cross_chain_tools:
        if tool.get('slug') == slug:
            tool_data = tool
            break

    if not tool_data:
        abort(404)

    # Coming soon tools - show 404 for now
    if tool_data.get('status') == 'coming_soon':
        abort(404)

    # Available tools with mock pages (none currently live except Reply Assistant)
    abort(404)

@tools_bp.route('/')
def tools():
    """Tools page with cross-chain infrastructure tools"""
    template_str = '''
{% extends "base.html" %}

{% block title %}Tools - Web3Fuel.io{% endblock %}

{% block content %}
<!-- Search and Filter Section -->
<section class="search-section">
    <div class="container">
        <div class="search-container">
            <div class="search-header">
                <p class="search-subtitle">Practical tools for analyzing cross-chain infrastructure, visualizing data, and monitoring blockchain security.</p>
            </div>
            <div class="search-bar">
                <input type="text" id="search-input" placeholder="Search tools..." class="search-input">
                <button id="search-button" class="search-button">🔍</button>
                <button id="clear-search" class="clear-button" style="display: none;">✕</button>
            </div>
            <div class="tag-filters">
                <button class="tag-btn active" data-tag="">All Tools</button>
                {% set all_tags = [] %}
                {% for tool in cross_chain_tools %}
                    {% if tool.status == 'live' or tool.status == 'beta' %}
                        {% for tag in tool.tags %}
                            {% if tag not in all_tags %}
                                {% set _ = all_tags.append(tag) %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                {% for tag in all_tags|sort %}
                <button class="tag-btn" data-tag="{{ tag }}">{{ tag }}</button>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

<!-- Tools Section -->
<section class="tools-section">
    <div class="container">
        <div class="no-results" id="no-results" style="display: none;">
            <p>No tools found matching your search criteria.</p>
        </div>
        <div class="tools-grid" id="tools-grid">
            {% for tool in cross_chain_tools %}
            <article class="tool-card {% if tool.status == 'coming_soon' %}coming-soon{% endif %}"
                     data-title="{{ tool.title|lower }}"
                     data-description="{{ tool.description|lower }}"
                     data-tags="{{ tool.tags|join(',')|lower }}">
                <h3 class="tool-title">{{ tool.title }}</h3>

                <div class="tool-description">
                    <p class="description-text">{{ tool.description }}</p>
                    <button class="read-more-btn" onclick="toggleDescription(this)">Read More</button>
                    <div class="tool-meta">
                        <div class="tool-tags">
                            {% for tag in tool.tags %}
                            <span class="tag">{{ tag }}</span>
                            {% endfor %}
                        </div>
                        <div class="tool-status">
                            {% if tool.status == 'live' %}
                            <span class="status-badge live">Live</span>
                            {% elif tool.status == 'beta' %}
                            <span class="status-badge beta">Beta</span>
                            {% elif tool.status == 'coming_soon' %}
                            <span class="status-badge coming-soon">Coming Soon</span>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="tool-value">
                    <span class="value-text">💡 {{ tool.why_valuable }}</span>
                </div>

                <div class="tool-actions">
                    {% if tool.status == 'live' %}
                    <a href="{{ url_for('tools.tool', slug=tool.slug) }}" class="action-btn primary">
                        Launch Tool
                    </a>
                    {% elif tool.status == 'beta' %}
                    <a href="{{ url_for('tools.tool', slug=tool.slug) }}" class="action-btn primary beta">
                        Try Beta
                    </a>
                    {% elif tool.status == 'coming_soon' %}
                    <button class="action-btn primary disabled" disabled>
                        Coming Soon
                    </button>
                    {% endif %}
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
</section>

<style>
/* Search Section */
.search-section {
    padding: 40px 0 20px 0;
    background: transparent;
}

.search-container {
    max-width: 1200px;
    margin: 0 auto;
    text-align: center;
}

.search-header {
    padding-top: 40px;
    margin-bottom: 50px;
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
}

.search-subtitle {
    font-size: 24px;
    color: #ffffff;
    margin: 0 auto;
    line-height: 1.5;
    font-weight: 550;
    max-width: 80%;
}

.search-bar {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    margin-bottom: 25px;
    flex-wrap: wrap;
}

.search-input {
    flex: 1;
    min-width: 300px;
    max-width: 500px;
    padding: 14px 20px;
    background: rgba(0, 0, 0, 0.6);
    border: 2px solid var(--border-color, #27272a);
    border-radius: 8px;
    color: #ffffff;
    font-size: 16px;
    transition: all 0.3s ease;
}

.search-input:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 15px rgba(0, 255, 234, 0.3);
}

.search-input::placeholder {
    color: var(--text-muted, #a1a1aa);
}

.search-button {
    padding: 14px 20px;
    background: linear-gradient(45deg, var(--primary), var(--secondary));
    color: black;
    font-weight: 600;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s ease;
    font-size: 16px;
}

.search-button:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(0, 255, 234, 0.4);
}

.clear-button {
    padding: 14px 16px;
    background: transparent;
    color: var(--primary);
    border: 2px solid var(--primary);
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.3s ease;
    font-size: 16px;
}

.clear-button:hover {
    background: var(--primary);
    color: black;
    transform: translateY(-2px);
}

.tag-filters {
    display: flex;
    justify-content: center;
    gap: 10px;
    flex-wrap: wrap;
}

.tag-btn {
    padding: 8px 16px;
    background: rgba(0, 0, 0, 0.6);
    border: 2px solid var(--border-color, #27272a);
    border-radius: 20px;
    color: #a1a1aa;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.3s ease;
}

.tag-btn:hover {
    border-color: var(--primary);
    color: var(--primary);
    transform: translateY(-2px);
}

.tag-btn.active {
    background: rgba(0, 255, 234, 0.2);
    border-color: var(--primary);
    color: var(--primary);
}

/* No Results */
.no-results {
    text-align: center;
    color: #a1a1aa;
    font-size: 16px;
    padding: 40px 20px;
}

/* Tools Section Styles - Grid Layout */
.tools-section {
    padding: 20px 0 60px 0;
    background: transparent;
}

.tools-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 25px;
    max-width: 1200px;
    margin: 0 auto;
}

.tool-card {
    background: rgba(0, 0, 0, 0.6);
    border: 2px solid var(--border-color, #27272a);
    border-radius: 16px;
    padding: 25px;
    box-shadow: 0 4px 20px rgba(0, 255, 234, 0.1);
    transition: all 0.3s ease;
    backdrop-filter: blur(10px);
    position: relative;
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

.tool-card::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 3px;
    background: linear-gradient(90deg, var(--primary), var(--secondary));
}

.tool-card:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 30px rgba(0, 255, 234, 0.2);
    border-color: var(--primary);
}

.tool-card.hidden {
    display: none;
}

.tool-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 12px;
    gap: 10px;
}

.tool-tags {
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
    flex: 1;
}

.tag {
    background: rgba(0, 255, 234, 0.2);
    color: var(--primary);
    padding: 3px 10px;
    border-radius: 20px;
    font-size: 10px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    border: 1px solid rgba(0, 255, 234, 0.3);
}

.tool-status {
    flex-shrink: 0;
}

.status-badge {
    display: inline-block;
    padding: 4px 10px;
    border-radius: 20px;
    font-size: 10px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.status-badge.live {
    background: rgba(34, 197, 94, 0.2);
    color: #22c55e;
    border: 1px solid rgba(34, 197, 94, 0.3);
}

.status-badge.beta {
    background: rgba(245, 158, 11, 0.2);
    color: #f59e0b;
    border: 1px solid rgba(245, 158, 11, 0.3);
}

.status-badge.coming-soon {
    background: rgba(156, 163, 175, 0.2);
    color: #9ca3af;
    border: 1px solid rgba(156, 163, 175, 0.3);
}

.tool-title {
    font-size: 20px;
    font-weight: 700;
    color: var(--text, #ffffff);
    margin: 0 0 12px 0;
    line-height: 1.3;
    background: linear-gradient(45deg, var(--primary), var(--secondary));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.tool-description {
    margin-bottom: 15px;
    flex: 1;
}

.tool-description .description-text {
    font-size: 14px;
    line-height: 1.6;
    color: #e2e8f0;
    margin: 0 0 8px 0;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    transition: all 0.3s ease;
}

.tool-description.expanded .description-text {
    display: block;
    -webkit-line-clamp: unset;
    overflow: visible;
}

.read-more-btn {
    background: none;
    border: none;
    color: var(--primary);
    font-size: 11px;
    font-weight: 600;
    cursor: pointer;
    padding: 0;
    margin-top: 8px;
    transition: all 0.2s ease;
    display: block;
}

.read-more-btn:hover {
    text-decoration: underline;
    opacity: 0.8;
}

.tool-value {
    margin-bottom: 15px;
    padding: 12px;
    background: rgba(0, 255, 234, 0.05);
    border: 1px solid rgba(0, 255, 234, 0.15);
    border-radius: 8px;
}

.value-text {
    font-size: 13px;
    color: var(--primary);
    line-height: 1.4;
}

.tool-actions {
    margin-top: auto;
}

.action-btn {
    padding: 10px 20px;
    border-radius: 8px;
    font-size: 13px;
    font-weight: 600;
    text-decoration: none;
    border: none;
    cursor: pointer;
    transition: all 0.3s ease;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 100%;
}

.action-btn.primary {
    background: linear-gradient(45deg, var(--primary), var(--secondary));
    color: black;
    font-weight: 700;
    box-shadow: 0 4px 15px rgba(0, 255, 234, 0.3);
}

.action-btn.primary:hover:not(.disabled) {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(0, 255, 234, 0.5);
    color: white;
}

.action-btn.primary.beta {
    background: linear-gradient(45deg, #f59e0b, #fbbf24);
    color: black;
}

.action-btn.primary.beta:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px rgba(245, 158, 11, 0.5);
    color: white;
}

.action-btn.disabled {
    background: rgba(255, 255, 255, 0.1);
    color: var(--text-muted, #a1a1aa);
    cursor: not-allowed;
    opacity: 0.6;
    border: 2px solid rgba(255, 255, 255, 0.1);
}

/* Coming Soon Tool Styling */
.tool-card.coming-soon {
    opacity: 0.6;
}

.tool-card.coming-soon:hover {
    transform: none;
    box-shadow: 0 4px 20px rgba(0, 255, 234, 0.05);
    border-color: rgba(255, 255, 255, 0.2);
}

.tool-card.coming-soon .tool-title {
    color: #a1a1aa;
    background: none;
    -webkit-background-clip: initial;
    -webkit-text-fill-color: initial;
    background-clip: initial;
}

.tool-card.coming-soon .tool-description .description-text {
    color: #71717a;
}

.tool-card.coming-soon .tag {
    background: rgba(255, 255, 255, 0.1);
    color: #a1a1aa;
    border-color: rgba(255, 255, 255, 0.1);
}

.tool-card.coming-soon .tool-value {
    background: rgba(255, 255, 255, 0.03);
    border-color: rgba(255, 255, 255, 0.1);
}

.tool-card.coming-soon .value-text {
    color: #71717a;
}

.tool-card.coming-soon .read-more-btn {
    color: #71717a;
}

/* Animations */
.fade-in-up {
    opacity: 0;
    transform: translateY(20px);
    animation: fadeInUp 0.5s ease forwards;
}

@keyframes fadeInUp {
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.tool-card.coming-soon.fade-in-up {
    animation: fadeInUpDimmed 0.5s ease forwards;
}

@keyframes fadeInUpDimmed {
    to {
        opacity: 0.6;
        transform: translateY(0);
    }
}

/* Responsive Design */
@media (max-width: 1024px) {
    .tools-grid {
        grid-template-columns: repeat(2, 1fr);
        gap: 20px;
        max-width: 800px;
    }
}

@media (max-width: 768px) {
    .search-section {
        padding: 30px 0 15px 0;
    }

    .search-subtitle {
        font-size: 20px;
    }

    .search-bar {
        flex-direction: row;
        align-items: center;
        position: relative;
    }

    .search-input {
        min-width: 100%;
        padding-right: 45px;
    }

    .search-button {
        display: none;
    }

    .clear-button {
        position: absolute;
        right: 10px;
        padding: 8px 12px;
        width: auto;
        font-size: 14px;
    }

    .tag-filters {
        justify-content: center;
    }

    .tools-grid {
        grid-template-columns: 1fr;
        gap: 20px;
        max-width: 100%;
    }

    .tool-card {
        padding: 20px;
    }

    .tool-title {
        font-size: 18px;
    }
}

@media (max-width: 480px) {
    .search-subtitle {
        font-size: 18px;
    }

    .tool-card {
        padding: 18px;
    }

    .tool-title {
        font-size: 17px;
    }

    .tool-description p {
        font-size: 13px;
    }

    .tag-btn {
        padding: 6px 12px;
        font-size: 12px;
    }
}
</style>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    // Share tool function
    function shareTool(title, description) {
        if (navigator.share) {
            navigator.share({
                title: title,
                text: description,
                url: window.location.href
            }).catch(err => console.log('Error sharing:', err));
        } else {
            // Fallback for browsers without native sharing
            const url = window.location.href;
            const text = `Check out this tool: ${title} - ${description}`;

            if (navigator.clipboard) {
                navigator.clipboard.writeText(`${text}\\n\\n${url}`).then(() => {
                    alert('Tool link copied to clipboard!');
                });
            } else {
                // Final fallback
                const textArea = document.createElement('textarea');
                textArea.value = `${text}\\n\\n${url}`;
                document.body.appendChild(textArea);
                textArea.select();
                document.execCommand('copy');
                document.body.removeChild(textArea);
                alert('Tool link copied to clipboard!');
            }
        }

        // Track sharing
        if (typeof gtag !== 'undefined') {
            gtag('event', 'tool_share', {
                'event_category': 'tools',
                'event_label': title
            });
        }
    }

    // Toggle description expand/collapse
    function toggleDescription(button) {
        const description = button.parentElement;
        const isExpanded = description.classList.contains('expanded');

        if (isExpanded) {
            description.classList.remove('expanded');
            button.textContent = 'Read More';
        } else {
            description.classList.add('expanded');
            button.textContent = 'Show Less';
        }
    }

    // Search and filter functionality
    let currentSearch = '';
    let currentTag = '';

    function initializeFilters() {
        const searchInput = document.getElementById('search-input');
        const searchButton = document.getElementById('search-button');
        const clearButton = document.getElementById('clear-search');

        // Search input events
        searchInput.addEventListener('input', function() {
            if (this.value.trim() === '') {
                clearSearch();
            } else {
                clearButton.style.display = 'block';
            }
        });

        searchInput.addEventListener('keypress', function(e) {
            if (e.key === 'Enter') {
                performSearch();
            }
        });

        searchButton.addEventListener('click', performSearch);
        clearButton.addEventListener('click', clearSearch);

        // Tag filter buttons
        document.querySelectorAll('.tag-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                const tag = this.getAttribute('data-tag');
                selectTag(tag);
            });
        });
    }

    function performSearch() {
        const searchInput = document.getElementById('search-input');
        currentSearch = searchInput.value.trim().toLowerCase();

        if (currentSearch) {
            document.getElementById('clear-search').style.display = 'block';
        }

        filterTools();
    }

    function clearSearch() {
        const searchInput = document.getElementById('search-input');
        const clearButton = document.getElementById('clear-search');

        searchInput.value = '';
        currentSearch = '';
        clearButton.style.display = 'none';
        filterTools();
    }

    function selectTag(tag) {
        currentTag = tag;

        // Update active button
        document.querySelectorAll('.tag-btn').forEach(btn => {
            btn.classList.remove('active');
            if (btn.getAttribute('data-tag') === tag) {
                btn.classList.add('active');
            }
        });

        filterTools();
    }

    function filterTools() {
        const tools = document.querySelectorAll('.tool-card');
        const noResults = document.getElementById('no-results');
        let visibleCount = 0;

        tools.forEach((tool, index) => {
            const title = tool.getAttribute('data-title') || '';
            const description = tool.getAttribute('data-description') || '';
            const tags = tool.getAttribute('data-tags') || '';

            // Check search match
            let searchMatch = true;
            if (currentSearch) {
                searchMatch = title.includes(currentSearch) ||
                              description.includes(currentSearch) ||
                              tags.includes(currentSearch);
            }

            // Check tag match
            let tagMatch = true;
            if (currentTag) {
                tagMatch = tags.toLowerCase().includes(currentTag.toLowerCase());
            }

            // Show/hide based on filters
            if (searchMatch && tagMatch) {
                tool.classList.remove('hidden');
                tool.style.animationDelay = `${visibleCount * 0.1}s`;
                visibleCount++;
            } else {
                tool.classList.add('hidden');
            }
        });

        // Show/hide no results message
        if (visibleCount === 0) {
            noResults.style.display = 'block';
        } else {
            noResults.style.display = 'none';
        }
    }

    // Initialize on page load
    document.addEventListener('DOMContentLoaded', function() {
        initializeFilters();

        // Add fade-in animations to tools on load
        const tools = document.querySelectorAll('.tool-card');
        tools.forEach((tool, index) => {
            tool.classList.add('fade-in-up');
            tool.style.animationDelay = `${index * 0.1}s`;
        });

        // Enhance mobile touch interactions
        if ('ontouchstart' in window) {
            document.querySelectorAll('.action-btn').forEach(btn => {
                btn.style.webkitTapHighlightColor = 'rgba(0,123,255,0.2)';
            });
        }
    });
</script>
{% endblock %}
    '''
    return render_template_string(template_str, cross_chain_tools=cross_chain_tools, tools_metrics=tools_metrics)
